src/AppBundle/Form/Type/TagType.php
<?php
/**
 * Created by PhpStorm.
 * User: Guillaume
 * Date: 14/03/2018
 * Time: 11:55
 */

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TagType extends AbstractType {
    /** * {@inheritdoc} */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('name', null, array('label' => "Nom", 'attr' => array('class' => 'form-control')))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Tag',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getNom()
    {
        return 'tag';
    }
}

src/AppBundle/Controller/AccueilController.php
<?php
/**
 * Created by PhpStorm.
 * User: Guillaume
 * Date: 28/03/2018
 * Time: 19:30
 */

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\User;
use AppBundle\Entity\Chambre;

/**
 * Class AccueilController
 * @package AppBundle\Controller
 * @Route("/accueil")
 */
class AccueilController extends Controller
{
     /**
     * @param Request $request
     * @Route("/")
     * @Template("AppBundle:Accueil:index.html.twig")
     */
    public function indexAction(Request $request){
        /*$repositoryAllChambre = $this->getDoctrine()->getRepository(Chambre::class);
        $query = $repositoryAllChambre->createQueryBuilder('c')
            ->getQuery();
        $allChambres = $query->getArrayResult();

        echo json_encode($allChambres);*/

        $currentRole =  $this->getUser()->getRoles()[0];

        $em = $this->getDoctrine()->getManager();
        $hotels = $em->getRepository('AppBundle:Hotel')->findAll();

        $repository = $this->getDoctrine()->getRepository(Chambre::class);

        $query = $repository->createQueryBuilder('c')
            ->orderBy('c.id', 'DESC')
            ->setMaxResults(3)
            ->getQuery();
        $chambres = $query->getResult();

        return array(
            'username' => $this->getUser()->getUsername(),
            'chambres' => $chambres,
            'hotels' =>$hotels,
            'role' => $currentRole,
        );
    }

    /**
     * @param Request $request
     * @Route("/error")
     * @Template("AppBundle:Accueil:errorRole.html.twig")
     */
    public function errorroleAction(Request $request){

    }
}

src/AppBundle/Resources/views/Accueil/errorRole.html.twig
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<style>
    @import url('https://fonts.googleapis.com/css?family=Lobster|Open+Sans');

    body{
        background: url(https://i.imgur.com/faFcxS1.png);
        background-color: #3E3E3E
        animation: scroll 70s infinite linear;
        font-family: "Open Sans", sans-serif;
        color: white;
    }
    @keyframes scroll{
        from {background-position: 0 0;}
        to {background-position: 100% 0;}
    }
    .logo{
        margin-left: auto;
        margin-right: auto;
        font-family: lobster;
        font-size: 120px;
        text-align: center;
    }
    .error{
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        font-size: 40px;
        background: rgba(0,0,0,.3);
        width:240px;
        border-radius:2px;
    }
    .error2{
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        background: rgba(0,0,0,.3);
        width: 300px;
        padding:10px;
        border-radius:2px;
    }
    a:link, a:visited, a:active{
        color: white;
        text-decoration: none;
    }
    .options{
        background: rgba(0,0,0,.3);
        width:150px;
        margin-right: auto;
        margin-left: auto;
        padding:10px;
        border-radius:2px;
    }
    back:hover{
        text-shadow: 0px 0px 10px #3498db;
    }
</style>
<div class="logo">
   Trip'Aquit
</div>
<br>
<div class="error">
    Error 403!
</div>
<br>
<div class="error2">
    Vous n'avez pas les droits d'accès à cette espace.</div>
<br>
<div class="options" align="center">
    <div id="back"><i class="fa fa-undo"></i>  <a href="{{ path('fos_user_security_logout') }}">Revenir au login</a>
    </div>
</div>
</html>

src/AppBundle/Resources/views/Accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if role == "ROLE_SUPER_ADMIN" %}
    <div class="text-center m-2 btnAddH">
        <a href="{{ path('admin_users') }}" class="btn btn-primary">Gestion des utilisateurs</a>
    </div>
    {% endif %}
    <div class="text-center" style="padding-left:260px;">
        <h2>Bienvenue <span class="text-primary">{{ username }}</span> sur l'administration de votre site web.</h2>
    </div>

    <div class="container" style="padding-left:260px;">
        <div class="row">
            <div class="col-4">
                <a href="{{ path('app_ville_index') }}" class="btn btn-outline-primary col-12" style="padding: 30px;">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <i class="fa fa-globe fa-3x" aria-hidden="true"></i>
                            </div>
                            <div class="col-12 text-center">
                                <h5>Gestion les villes</h5>
                            </div>
                            <div class="col-12 text-center">
                                Ajouter, modifier, <br>supprimer une ville
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-4">
                <a href="{{ path('app_hotel_index') }}" class="btn btn-outline-primary col-12" style="padding: 30px;">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <i class="fa fa-h-square fa-3x" aria-hidden="true"></i>
                            </div>
                            <div class="col-12 text-center">
                                <h5>Gestion des hôtels</h5>
                            </div>
                            <div class="col-12 text-center">
                                Ajouter, modifier, <br>supprimer un hôtel
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-4">
                <a href="{{ path('app_chambre_index') }}" class="btn btn-outline-primary col-12" style="padding: 30px;">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <i class="fa fa-bed fa-3x" aria-hidden="true"></i>
                            </div>
                            <div class="col-12 text-center">
                                <h5>Gestion des chambres</h5>
                            </div>
                            <div class="col-12 text-center">
                                Ajouter, modifier, <br>supprimer une chambre
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>


    <div class="container" style="padding-left:260px;">
        <h2 class="text-center p-3">Dernières chambres mise en ligne</h2>
        <div class="row">
            {% for chambre in chambres %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ asset('/upload/image/chambre/' ~ chambre.image1) }}" style="height:250px;width:250px;margin:auto;" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ chambre.nom }}</h5>
                        <p class="card-text">
                            Nb M² : {{ chambre.nbmcarre }}<br>
                            Nb chambre : {{ chambre.nbchambre }}<br>
                            Nb pièce : {{ chambre.nbpiece }}<br>
                            Nb personne : {{ chambre.nbpersonne }}<br>
                            Hôtel : {{ chambre.hotel.nom }}<br>
                            {% for hotel in hotels %}
                                {% if chambre.hotel.id == hotel.id %}
                                    Ville : {{ hotel.ville.nom }}
                                {% endif %}
                            {% endfor %}
                        <p class="text-right">{{ chambre.datepublication|date('Y-m-d à H:i:s') }}</p>
                        </p>
                        <a href="{{ path('app_chambre_show', {'id': chambre.id }) }}" class="btn btn-primary">Voir cette chambre</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}